Map("n", "<leader>gst", "<cmd>Git status<cr>", Opts)
Map("n", "<leader>gau", "<cmd>Git add -u<cr>", Opts)
Map("n", "<leader>gw", "<cmd>Gwrite<cr>", Opts)
Map("n", "<leader>gc", "<cmd>Git commit<cr>", Opts)
Map("n", "<leader>gp", "<cmd>Git push<cr>", Opts)
Map("n", "<leader>gl", "<cmd>Git pull<cr>", Opts)
Map("n", "<leader>gd", "<cmd>Git diff<cr>", Opts)
Map("n", "<leader>gds", "<cmd>Gvdiffsplit<cr>", Opts)
Map("n", "<leader>gl", "<cmd>Git log<cr>", Opts)
Map("n", "<leader>gb", "<cmd>GBrowse<cr>", Opts)
